# Generated by Django 3.2.12 on 2022-03-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vedant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='carrer',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='greeting_1',
            new_name='greetings_1',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='greeting_2',
            new_name='greetings_2',
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vedant.category')),
            ],
        ),
    ]
